version: 2


jobs:
  build:
    docker:
      - image: circleci/python:3.6.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: install dependencies
          command: |
            python3 -m venv venv
            . venv/bin/activate
            pip install -r requirements.txt

      - save_cache:
          paths:
            - ./venv
          key: v1-dependencies-{{ checksum "requirements.txt" }}

      - run:
          name: run tests
          command: |
            . venv/bin/activate
            python tests/demo_test.py

      - run:
          name: coverage tests
          command: |
            . venv/bin/activate
            pip install codecov
            coverage run tests/demo_test.py


      - run:
          name: run install
          command: |
            . venv/bin/activate
            python setup.py install
            multi_run.py -h

      - run:
          name: store_test
          command: |
            mkdir test-reports
            . venv/bin/activate
            pip install codecov
            codecov
            coverage report && coverage xml -o test-reports/coverage.xml
      - store_test_results:
         path: test-reports
      - store_artifacts:
         path: test-reports

  anaconda:
    docker:
      - image: continuumio/miniconda3
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          key: v1-dependencies-{{ checksum "requirements.txt" }}
      - run:
          name: build anaconda
          command: |
            conda config --add channels conda-forge
            conda config --set always_yes true
            conda config --set quiet true
            conda install conda-build
            conda build .anaconda/meta.yaml

workflows:
  version: 2
  build_and_conda_test:
    jobs:
      - build
      - anaconda:
        require:
          - build









