{% set version = "0.1.6.alpha" %}


package:
  name: animal-courier
  version: {{ version }}

build:
  number: 0
  script: $PYTHON setup.py install --single-version-externally-managed --record=record.txt

source:
#  git_url: https://github.com/btrspg/Animal-Courier.git
  url: https://github.com/dota2-BioTools/Animal-Courier/archive/v{{ version }}.tar.gz


requirements:
  build:
    - python
    - plotly
  host:
    - python
    - zlib
    - bzip2
    - curl
    - certifi >=2018.11.29
    - numpy >=1.15.4
    - pandas >=0.23.4
    - plotly




  run:
    - python
    - zlib
    - bzip2
    - curl
    - certifi >=2018.11.29
    - numpy >=1.15.4
    - pandas >=0.23.4
    - plotly


test:
  command:
    - multi_run.py -h


about:
  home: https://github.com/dota2-BioTools/Animal-Courier
  license: MIT
  summary: An open source shell run control