{% set version = "0.1.3.beta" %}


package:
  name: animal-courier
  version: {{ version }}

build:
  number: 0
  script: $PYTHON setup.py install

source:
  url: https://github.com/dota2-BioTools/Animal-Courier/archive/v{{ version }}.tar.gz


requirements:
  build:
    - python
  host:
    - python
    - zlib
    - bzip2
    - curl
    - certifi >=2018.11.29
    - numpy >=1.15.4
    - pandas >=0.23.4
    - plotly



  run:
    - python
    - zlib
    - bzip2
    - curl
    - certifi >=2018.11.29
    - numpy >=1.15.4
    - pandas >=0.23.4
    - plotly

test:
  command:
    - multi_run.py -h


about:
  home: https://github.com/dota2-BioTools/Animal-Courier
  license: MIT License
  summary: An open source shell run control