{% set version = "0.1.1.alpha" %}


package:
  name: animal-courier
  version: {{ version }}

build:
  number: 0
  script: $PYTHON setup.py install

source:
  url: https://github.com/dota2-BioTools/Animal-Courier/archive/v{{ version }}.tar.gz


requirements:
  build:
    - python >=3.5
  host:
    - python >=3.5
    - zlib
    - bzip2
    - curl
    - certifi >=2018.11.29
    - numpy >=1.15.4



  run:
    - python >=3.5
    - zlib
    - bzip2
    - curl
    - certifi >=2018.11.29
    - numpy >=1.15.4

test:
  command:
    - multi_run.py -h


about:
  home: https://github.com/dota2-BioTools/Animal-Courier
  license: MIT License (MIT)
  summary: An open source shell run control